In [87]:
import numpy as np
from sklearn import datasets

In [88]:
#The iris dataset is a classic and very easy multi-class classification dataset.
#This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray
#The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.
iris = datasets.load_iris()
#samples of the flowers [Sepal length, Sepal width, Petal length, Petal width]
iris_x = iris.data
#clasification of the flowers 0 1 2 each correspond to one of the species (setosa,versicolor,virginica)
iris_y = iris.target
#Finds the unique elements of the array
np.unique(iris_y)

array([0, 1, 2])

In [89]:
# Split iris data in train and test data
# A random permutation, to split the data randomly
#iris_x has to be an np array in order to be indexed
#iris_y has to be an np array in order to be indexed
np.random.seed(0)
#creates a random array with size the x dimension
indices = np.random.permutation(len(iris_x))

#All the indexes from the length of array -10 until the first index
iris_x_train = iris_x[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
#Ten last indexes counting from the last of the index array
iris_x_test = iris_x[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

In [90]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_x_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [91]:
from sklearn.metrics import accuracy_score
knn.predict(iris_x_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [92]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [93]:
accuracy_score(iris_y_test, knn.predict(iris_x_test))

0.90000000000000002

In [94]:
#Error is the total probability minus the accuracy score
print("Error of the classifier:")
1-accuracy_score(iris_y_test, knn.predict(iris_x_test))

Error of the classifier:


0.099999999999999978

In [103]:
#k = list(range(1,len(iris_x_train)))
#print(k)
#find optimal k 
optimal_k = 0;
max_accuracy = 0.0;
pred_x = []
#Tests with more partitions are required to find optimal k given that there are multiple values
#that predict with total accuracy for the test set previously created for this case I'm going
# to use the smallest k that predicts correctly all the results.
for k in range(1,len(iris_x_train)):
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(iris_x_train, iris_y_train)
    if(accuracy_score(iris_y_test, neigh.predict(iris_x_test)) > max_accuracy):
        optimal_k = k
        max_accuracy = accuracy_score(iris_y_test, neigh.predict(iris_x_test))
        pred_x = neigh.predict(iris_x_test)
print("Optimal k:")
optimal_k


Optimal k:


8

In [102]:
#This is the error obtained for the given test dataset it might be higher for other test sets. 
print("Error of the classifier with k = "+ str(optimal_k))
1.0-max_accuracy

Error of the classifier with k = 8


0.0

In [104]:
print("Predicted values for k = "+ str(optimal_k))
pred_x


Predicted values for k = 8


array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [105]:
print("expected values:")
iris_y_test


expected values:


array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])