In [18]:
import numpy as np

class MajorityClassClassifier:

    majorityClass = 0
    def  __init__(self):        
        majorityClass = 0
    
    def fit(self,X,Y):
        # TODO|
        dict = {}
        for y in Y:
            if y not in dict:
                dict[y] = 1
            else:
                dict[y] = dict[y] + 1
        mv = 0
        for k, v in dict.items():
            if v>=mv:
                mv = v
                self.majorityClass=k
        return self

    def predict(self,X):
        return np.full((len(X)),self.majorityClass, dtype=np.int)
    

In [19]:
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
class Test:
    iris = datasets.load_iris()
    iris_x = iris.data
    iris_y = iris.target
    np.unique(iris_y)
    indices = np.random.permutation(len(iris_x))
    iris_x_train = iris_x[indices[:-10]]
    iris_y_train = iris_y[indices[:-10]]
    iris_x_test = iris_x[indices[-10:]]
    iris_y_test = iris_y[indices[-10:]]
    mcc = MajorityClassClassifier()
    mcc.fit(iris_x_train,iris_y_train)
    print("Prediction:")
    print(mcc.predict(iris_x_test)) 
    print("Expected results:")
    print(iris_y_test)
    print("accuracy:")
    print(accuracy_score(iris_y_test, mcc.predict(iris_x_test)))
    print("error:")
    print(1-accuracy_score(iris_y_test, mcc.predict(iris_x_test)))
    print("confusion matrix:")
    print(confusion_matrix(iris_y_test, mcc.predict(iris_x_test)))

Prediction:
[1 1 1 1 1 1 1 1 1 1]
Expected results:
[2 1 1 0 2 2 0 0 2 0]
accuracy:
0.2
error:
0.8
confusion matrix:
[[0 4 0]
 [0 2 0]
 [0 4 0]]
matthews correlation coefficient:


ValueError: multiclass is not supported